import type { Template } from '@/types';

// These are the default templates used when DB is not yet seeded
// previewUrl and baseImageUrl point to /mockups/ public folder (placeholder PNGs)
// In production, upload real mockup base images to Supabase Storage templates/ bucket
// and update these URLs accordingly.

export const DEFAULT_TEMPLATES: Template[] = [
  {
    id: 'tpl-001',
    slug: 'black-tshirt-front',
    name: 'Black T-Shirt — Front',
    category: 'tshirt',
    previewUrl: '/mockups/tshirt-black-preview.png',
    baseImageUrl: '/mockups/tshirt-black-base.png',
    width: 1000,
    height: 1200,
    printArea: { x: 300, y: 280, width: 400, height: 450, rotation: 0 },
    blendMode: 'multiply',
    tags: ['tshirt', 'apparel', 'black'],
  },
  {
    id: 'tpl-002',
    slug: 'white-tshirt-front',
    name: 'White T-Shirt — Front',
    category: 'tshirt',
    previewUrl: '/mockups/tshirt-white-preview.png',
    baseImageUrl: '/mockups/tshirt-white-base.png',
    width: 1000,
    height: 1200,
    printArea: { x: 300, y: 280, width: 400, height: 450, rotation: 0 },
    blendMode: 'multiply',
    tags: ['tshirt', 'apparel', 'white'],
  },
  {
    id: 'tpl-003',
    slug: 'a3-poster',
    name: 'A3 Poster',
    category: 'poster',
    previewUrl: '/mockups/poster-a3-preview.png',
    baseImageUrl: '/mockups/poster-a3-base.png',
    width: 794,
    height: 1123,
    printArea: { x: 40, y: 40, width: 714, height: 1043, rotation: 0 },
    blendMode: 'normal',
    tags: ['poster', 'print', 'a3'],
  },
  {
    id: 'tpl-004',
    slug: 'white-mug',
    name: 'White Mug — 11oz',
    category: 'mug',
    previewUrl: '/mockups/mug-white-preview.png',
    baseImageUrl: '/mockups/mug-white-base.png',
    width: 900,
    height: 700,
    printArea: { x: 200, y: 180, width: 500, height: 280, rotation: 0 },
    blendMode: 'multiply',
    tags: ['mug', 'drinkware'],
  },
  {
    id: 'tpl-005',
    slug: 'outdoor-signboard',
    name: 'Outdoor Signboard',
    category: 'signboard',
    previewUrl: '/mockups/signboard-preview.png',
    baseImageUrl: '/mockups/signboard-base.png',
    width: 1200,
    height: 800,
    printArea: { x: 100, y: 80, width: 1000, height: 640, rotation: 0 },
    blendMode: 'normal',
    tags: ['signboard', 'outdoor', 'banner'],
  },
  {
    id: 'tpl-006',
    slug: 'grey-hoodie-front',
    name: 'Grey Hoodie — Front',
    category: 'tshirt',
    previewUrl: '/mockups/hoodie-grey-preview.png',
    baseImageUrl: '/mockups/hoodie-grey-base.png',
    width: 1000,
    height: 1300,
    printArea: { x: 310, y: 300, width: 380, height: 380, rotation: 0 },
    blendMode: 'multiply',
    tags: ['hoodie', 'apparel', 'grey'],
  },
  {
    id: 'tpl-007',
    slug: 'canvas-tote',
    name: 'Canvas Tote Bag',
    category: 'tote',
    previewUrl: '/mockups/tote-canvas-preview.png',
    baseImageUrl: '/mockups/tote-canvas-base.png',
    width: 900,
    height: 1000,
    printArea: { x: 250, y: 200, width: 400, height: 500, rotation: 0 },
    blendMode: 'multiply',
    tags: ['tote', 'bag', 'canvas'],
  },
  {
    id: 'tpl-008',
    slug: 'square-frame-poster',
    name: 'Square Framed Poster',
    category: 'poster',
    previewUrl: '/mockups/poster-square-preview.png',
    baseImageUrl: '/mockups/poster-square-base.png',
    width: 1000,
    height: 1000,
    printArea: { x: 80, y: 80, width: 840, height: 840, rotation: 0 },
    blendMode: 'normal',
    tags: ['poster', 'square', 'frame'],
  },
];
